### ISSUE TITLE
Highlight the repost icon on notes

### ISSUE THREAD

**Issue by dwebert** [hzrd149/nostrudel#65] opened 2023-11-15 20:24 UTC
Highlight the repost icon on notes if myself has reposted the note

![image](https://github.com/hzrd149/nostrudel/assets/18017148/7988c5d4-2107-4ccc-9666-40f4ca12e746)

**Comment by hzrd149** [comment] 2023-11-15 21:09
This *should* be an easy fix. but I'd like to find a more efficient way to load that data without loading all reposts for every note.
I've got ideas but this probably wont be fixed imminently

**Comment by hzrd149** [comment] 2023-11-18 16:51
Did a few tests with this and I don't think it will work. at least not without significantly slowing down the client or DDOSing the relays

The issue is to know if I've already reposted each event in the timeline I have to make a separate request to at least 2-3 relays and there doesn't seem to be any way to batch them.
This results in a lot of network traffic and many relays reject the requests because there are to many happening at once.

It might make sense to scale this back though and maybe show a warning if you've already reposted the note when you click the button

**Comment by dwebert** [comment] 2023-11-18 20:42
Well let's keep searching/thinking.  primal.net and Amethyst found a way :)

**Comment by dwebert** [comment] 2023-11-18 20:45
But in the meanwhile could we "activate" it in "the drawer" when it shows the note? 
And also when you just have one note (in "fullscreen"/http://localhost:8080/#/n/note1.......)

**Comment by hzrd149** [comment] 2024-01-29 17:19
This should now be working in the alpha version

**Comment by hzrd149** [comment] 2024-02-03 19:05
Released

**Closed by hzrd149** 2024-02-03 19:05 UTC
Labels: enhancement
